# Generated by Django 3.2.9 on 2021-11-08 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('Phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('Phone_type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('FAX', 'Fax')], default=1, max_length=10)),
                ('Area_code', models.IntegerField()),
                ('Number', models.IntegerField()),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbook.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('Date_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_type', models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary')], max_length=12)),
                ('date_val', models.DateField(max_length=50)),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbook.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], default=1, max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Zip', models.IntegerField(default=0)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbook.contact')),
            ],
        ),
    ]
