# Generated by Django 3.2.9 on 2021-11-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_val',
            field=models.CharField(max_length=50),
        ),
    ]
